#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void setup_make_conf() {
    FILE *fp = fopen("/etc/portage/make.conf", "a");
    if (fp == NULL) {
        perror("Error opening make.conf");
        return;
    }

    fprintf(fp,
        "\n# --- Generated by Custom Gentoo Installer ---\n"
        "COMMON_FLAGS=\"-O3 -march=native -pipe\"\n"
        "CFLAGS=\"${COMMON_FLAGS}\"\n"
        "CXXFLAGS=\"${COMMON_FLAGS}\"\n"
        "FCFLAGS=\"${COMMON_FLAGS}\"\n"
        "FFLAGS=\"${COMMON_FLAGS}\"\n\n"
        "# Build parallelism\n"
        "MAKEOPTS=\"-j4 -l5\"\n\n"
        "# Language\n"
        "LC_MESSAGES=C.UTF-8\n\n"
        "# Bootloader\n"
        "GRUB_PLATFORMS=\"efi-64\"\n\n"
        "# USE flags\n"
        "USE=\"elogind wayland lto -systemd\"\n\n"
        "# Graphics\n"
        "VIDEO_CARDS=\"intel\"\n\n"
        "# CPU flags matching i5-7200U\n"
        "CPU_FLAGS_X86=\"aes avx avx2 fma mmx mmxext pclmulqdq popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3\"\n\n"
        "# Binpkg & Licenses\n"
        "FEATURES=\"buildpkg\"\n"
        "PKGDIR=\"/var/cache/binpkgs\"\n"
        "ACCEPT_LICENSE=\"* -@EULA @BINARY-REDISTRIBUTABLE\"\n"
    );

    fclose(fp);
    printf("make.conf successfully updated!\n");
}


int main() {
    int kernel;
    char GRUB[100];
    char username [64];
    char cmd[256];
    char EFI[256];
    char efi[100];
    char username1[100];
    char pkgs[10000];
    char PKGS[10000];
    char eselect[200];
    
  system("emerge-webrsync");
  setup_make_conf();
  printf("which kernel you want to run?\n");
  printf("1. gentoo-kernel-bin\n");
  printf("2. zenkernel\n");
  printf("3. copying kernel from LiveGUI\n");
  printf("choose (in numbers):- ");
  scanf("%d", &kernel);
  switch (kernel) {
           case 1:
            printf("installing kernel!\n");
            system("mkdir -p /etc/portage/package.accept_keywords");
            system("echo 'sys-kernel/installkernel dracut' >> /etc/portage/package.accept_keywords/installkernel");
            system("emerge --autounmask-write=y --autounmask-continue sys-kernel/gentoo-kernel-bin");
            break;
           case 2:
            printf("installing kernel!\n");
            system("mkdir -p /etc/portage/package.accept_keywords");
            system("echo \"sys-kernel/zen-sources ~amd64\" >> /etc/portage/package.accept_keywords/zen-kernel");
            system("emerge sys-kernel/zen-sources");
            system("emerge sys-kernel/genkernel");
            system("eselect kernel set $(eselect kernel list | grep 'zen' | awk -F'[][]' '{print $2}' | tr -d ' ')");
            system("genkernel all");
            break;
           case 3:
            printf("LiveGUI kernel copying isn't implemented yet.\n");
            break;
           default:
            printf("option not recognised");
            break;
  }
  printf("you want to install GRUB?:- ");
  scanf("%99s", GRUB);
  if (strcmp(GRUB, "yes") == 0) {
           printf("installing GRUB!\n");
           system("mkdir -p /boot/efi");
           printf("enter your EFI partition: ");
           scanf("%s", EFI);
           snprintf(efi, sizeof(efi), "mountpoint -q /boot/efi || mount %s /boot/efi", EFI);
           system(efi);
           system("emerge sys-boot/grub");
           printf("applying grub\n");
           system("grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=Gentoo_New");
           system("grub-mkconfig -o /boot/grub/grub.cfg");
  }
  else {
      printf("ehh skipping then, add later");
  }
  printf("installing firmware....\n");
  system("emerge sys-kernel/linux-firmware");
  printf(" enter your root password!\n");
  system("passwd root");

  printf("enter your username pls:- ");
  scanf("%63s", username);

  snprintf(cmd, sizeof(cmd), "useradd -m -G wheel,audio,video,input -s /bin/bash %s", username);
  system(cmd);
  snprintf(username1, sizeof(username1),"passwd %s", username);
  system(username1);
  printf("\nDo you want to install any other thing? (type if yes): ");
  fgets(pkgs, sizeof(pkgs), stdin);
  pkgs[strlen(pkgs) -1] = '\0';
  snprintf(PKGS, sizeof(PKGS), "ACCEPT_KEYWORDS=\"~amd64\" emerge %s", pkgs);
    
  system(PKGS);
  printf("its eselect time, do you want to add it? UwU\n");
  printf("type here:- ");
  fgets(eselect, sizeof(eselect), stdin);
  eselect[strlen(eselect) -1] = '\0';
  if (strcmp(eselect, "yes") == 0) {
      system("./eselect");
  }
  if (strcmp(eselect, "no") == 0) {
      printf("end then\n");
  }
  
  printf("\nYAY, INSTALLATION COMPLETED! YOU CAN NOW ENTER YOU GENTOO YIPPEE!!!\n");
return 0;
}
